/** Imágenes locales en `public/images/` (Unsplash + casos reales del cliente). */
export const MEDIA = {
  heroAvion: "/images/hero-avion.jpg",
  ctaViaje: "/images/cta-viaje.jpg",
  atmosferaPaisaje: "/images/atmosfera-paisaje.jpg",
  equipoReunion: "/images/equipo-reunion.jpg",
  familia: "/images/familia.jpg",
  documentacionEscritorio: "/images/documentacion-escritorio.jpg",
  documentos: "/images/documentos.jpg",
  graduacion: "/images/graduacion.jpg",
  viajeHorizonte: "/images/viaje-horizonte.jpg",
  ciudadCalle: "/images/ciudad-calle.jpg",
  familiaManos: "/images/familia-manos.jpg",
  profesional: "/images/profesional.jpg",
  asesoria: "/images/asesoria.jpg",
  estudioExpediente: "/images/estudio-expediente.jpg",
  salud: "/images/salud.jpg",
  ingenieria: "/images/ingenieria.jpg",
  docencia: "/images/docencia.jpg",
  graduacionCeremonia: "/images/graduacion-ceremonia.jpg",
  lagoCamino: "/images/lago-camino.jpg",
  oficina: "/images/oficina.jpg",
  montana: "/images/montana.jpg",
  /** Entregas y acompañamientos reales (material del cliente). */
  casos: {
    visaEntrega: "/images/casos/visa-entrega.jpg",
    parejaOficina: "/images/casos/pareja-oficina.jpg",
    residenciaPermanenteCdmx: "/images/casos/residencia-permanente-cdmx.jpg",
    familiaResidencias: "/images/casos/familia-residencias.jpg",
    tribunalFederal: "/images/casos/tribunal-federal.jpg",
    residenciaPermanenteSenora: "/images/casos/residencia-permanente-senora.jpg",
    inmHidalgoFamilia: "/images/casos/inm-hidalgo-familia.jpg",
    entregaTarjeta: "/images/casos/entrega-tarjeta.jpg",
    oficinaHidalgo: "/images/casos/oficina-hidalgo.jpg",
    familiaNinoTarjeta: "/images/casos/familia-nino-tarjeta.jpg",
  },
} as const;
