/** Imágenes locales en `public/images/` (optimizadas WebP donde aplica). */
export const MEDIA = {
  heroAvion: "/images/hero-avion.webp",
  ctaViaje: "/images/cta-viaje.webp",
  atmosferaPaisaje: "/images/atmosfera-paisaje.webp",
  equipoReunion: "/images/equipo-reunion.webp",
  familia: "/images/familia.webp",
  documentacionEscritorio: "/images/documentacion-escritorio.webp",
  documentos: "/images/documentos.webp",
  graduacion: "/images/graduacion.webp",
  viajeHorizonte: "/images/viaje-horizonte.webp",
  ciudadCalle: "/images/ciudad-calle.webp",
  familiaManos: "/images/familia-manos.webp",
  profesional: "/images/profesional.webp",
  asesoria: "/images/asesoria.webp",
  estudioExpediente: "/images/estudio-expediente.webp",
  salud: "/images/salud.webp",
  ingenieria: "/images/ingenieria.webp",
  docencia: "/images/docencia.webp",
  graduacionCeremonia: "/images/graduacion-ceremonia.webp",
  lagoCamino: "/images/lago-camino.webp",
  oficina: "/images/oficina.webp",
  montana: "/images/montana.webp",
  /** Entregas y acompañamientos reales (material del cliente). */
  casos: {
    visaEntrega: "/images/casos/visa-entrega.jpg",
    parejaOficina: "/images/casos/pareja-oficina.jpg",
    residenciaPermanenteCdmx: "/images/casos/residencia-permanente-cdmx.jpg",
    familiaResidencias: "/images/casos/familia-residencias.jpg",
    tribunalFederal: "/images/casos/tribunal-federal.jpg",
    residenciaPermanenteSenora: "/images/casos/residencia-permanente-senora.jpg",
    inmHidalgoFamilia: "/images/casos/inm-hidalgo-familia.jpg",
    entregaTarjeta: "/images/casos/entrega-tarjeta.jpg",
    oficinaHidalgo: "/images/casos/oficina-hidalgo.jpg",
    familiaNinoTarjeta: "/images/casos/familia-nino-tarjeta.jpg",
  },
} as const;
